<?= $this->doctype() ?>
<html lang="en">
    <?= require __DIR__.'/../include/public/head.phtml'; ?>
    <body>
        <div class="container">
            <?= include __DIR__.'/../include/public/navigation.phtml'; ?>
            <?= include __DIR__.'/../include/public/header.phtml'; ?>
            <?= $this->content ?>
            <?= include __DIR__.'/../include/public/footer.phtml'; ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
