<?= $this->doctype();?>
<html lang="en">
    <?php require __DIR__.'/../include/public/head.phtml'; ?>
    <body>
        <div class="container">
            <?php include __DIR__.'/../include/public/navigation.phtml'; ?>
            <?php include __DIR__.'/../include/public/header.phtml'; ?>
            <?= $this->content ?>
            <?php include __DIR__.'/../include/public/footer.phtml'; ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
